[package]
name = "llvm-rs"
version = "0.0.2"
authors = [ "Hyunsik Choi <hyunsik@apache.org>" ]
build = "build.rs"

[lib]
name = "llvm_rs"
path = "src/lib.rs"

[dependencies]
libc = "*"
llvm-sys = "*"

[build-dependencies]
gcc = "0.3.13"
semver = "0.1.20"