[package]
name = "llvm"
version = "0.0.2"
authors = [ "Hyunsik Choi <hyunsik@apache.org>" ]
build = "build.rs"

[lib]
name = "llvm"
path = "src/lib.rs"

[dependencies]
libc = "^0.2"
llvm-sys = "=0.2.2"

[build-dependencies]
gcc = "0.3.13"
semver = "0.1.20"
